[paths]
app_path = "Contents/Resources/app"
app_packages_path = "Contents/Resources/app_packages"
support_path = "Contents/Resources"
icon = "Contents/Resources/{{ cookiecutter.name }}.icns"
{% for extension, doctype in cookiecutter.document_types.items() %}
[paths.document_type.{{ extension }}]
icon = "Contents/Resources/{{ cookiecutter.name }}-{{ extension }}.icns"
{% endfor %}