[paths]
app_path = "{{ cookiecutter.formal_name }}.app/Contents/Resources/app"
app_packages_path = "{{ cookiecutter.formal_name }}.app/Contents/Resources/app_packages"
support_path = "{{ cookiecutter.formal_name }}.app/Contents/Resources/Support"
icon = "{{ cookiecutter.formal_name }}.app/Contents/Resources/{{ cookiecutter.name }}.icns"
{% for extension, doctype in cookiecutter.document_types.items() -%}
document_type_icon.doc = "{{ cookiecutter.formal_name }}.app/Contents/Resources/{{ cookiecutter.name }}-{{ extension }}.icns"
{% endfor %}